apiVersion: v1
kind: Secret
metadata:
  name: ftth-postgres-secret
  namespace: ftth
  labels:
    app.kubernetes.io/name: ftth
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: replace-with-strong-password
